# Generated by Django 4.2.1 on 2023-06-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cantidad_personas', models.CharField(max_length=2)),
                ('fecha_reserva', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
    ]
