# Generated by Django 4.2.1 on 2023-06-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_formulario_id_formulario_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_reserva', models.CharField(max_length=10)),
                ('cantidad_personas', models.CharField(max_length=2)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
    ]
