# Generated by Django 4.2.1 on 2023-06-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idTipoCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Tipo Cliente')),
                ('nombreTC', models.CharField(max_length=30, verbose_name='Descripción Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'tipoCliente',
                'verbose_name_plural': 'tipoClientes',
                'ordering': ['idTipoCliente'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Tipo Producto')),
                ('nombreTP', models.CharField(max_length=30, verbose_name='Descripción Producto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'tipoProducto',
                'verbose_name_plural': 'tipoProductos',
                'ordering': ['idTipoProducto'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio')),
                ('stockProducto', models.IntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('idTipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipoproducto', verbose_name='Código Tipo Producto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['idProducto', 'nombreProducto'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('dvRutCliente', models.CharField(max_length=1, verbose_name='DvRut Cliente')),
                ('nombreCliente', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('telefonoCliente', models.IntegerField(verbose_name='Teléfono Cliente')),
                ('emailCiente', models.EmailField(max_length=100, verbose_name='Email Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('idTipoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tipocliente', verbose_name='Código Tipo Cliente')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['rutCliente'],
            },
        ),
    ]
