# Generated by Django 4.2.1 on 2023-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen'),
        ),
    ]
