# Generated by Django 4.2.1 on 2023-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos', verbose_name='Imagen'),
        ),
    ]
