# Generated by Django 4.2.1 on 2023-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_producto_stockproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idTipoProducto',
            new_name='tipoProducto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=30, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='idTipoProducto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Tipo Producto'),
        ),
    ]
