# Generated by Django 4.2.1 on 2023-06-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_idtipoproducto_producto_tipoproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idTipoCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombreTC',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='crud.tipocliente', verbose_name='Tipo Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='emailCiente',
            field=models.CharField(max_length=100, verbose_name='Email Cliente'),
        ),
        migrations.AlterField(
            model_name='tipocliente',
            name='idTipoCliente',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Tipo Cliente'),
        ),
    ]
