# Generated by Django 4.2.1 on 2023-06-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_remove_cliente_idtipocliente_cliente_nombretc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='emailCiente',
            new_name='emailCliente',
        ),
    ]
