# Generated by Django 4.2.1 on 2023-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_emailciente_cliente_emailcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rutCliente',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Rut Cliente'),
        ),
    ]
